"""Consent-bound install, doctor and uninstall plans."""

from __future__ import annotations

import argparse
import hashlib
import json
import os
import shutil
import subprocess
import sys
from pathlib import Path
from typing import Any

from cortex_paths import build_paths
from process_ownership import classify, load_record
from version import current_version

ROOT = Path(__file__).resolve().parent.parent
STAGING_NAME = ".install-staging"


def _canonical(payload: dict[str, Any]) -> bytes:
    return json.dumps(payload, ensure_ascii=False, sort_keys=True, separators=(",", ":")).encode("utf-8")


def _hashed(payload: dict[str, Any]) -> dict[str, Any]:
    return {**payload, "plan_hash": hashlib.sha256(_canonical(payload)).hexdigest()}


def _human_pauses() -> list[dict[str, str]]:
    return [
        {"kind": "login", "detail": "ChatGPT login is manual in the dedicated profile."},
        {"kind": "terms", "detail": "Only the user may accept third-party terms."},
        {"kind": "extension", "detail": "Browser extensions require manual review and installation."},
        {"kind": "secrets", "detail": "Secrets are never requested or generated by this installer."},
        {"kind": "privilege", "detail": "sudo and privilege escalation are never executed."},
    ]


def _command(
    command_id: str,
    argv: list[str],
    official_url: str,
    disk_bytes: int,
    rollback: str,
) -> dict[str, Any]:
    if not argv or "sudo" in argv:
        raise ValueError("unsafe installer command")
    return {
        "id": command_id,
        "argv": argv,
        "official_url": official_url,
        "disk_bytes": disk_bytes,
        "rollback": rollback,
    }


def _owned_manifest_path() -> Path:
    return build_paths().home / "install" / "owned.json"


def _installed() -> bool:
    paths = build_paths()
    return (paths.home / "venv").is_dir() and _owned_manifest_path().is_file()


def build_install_plan(*, rebuild_ui: bool = False, ollama_model: str | None = None) -> dict[str, Any]:
    paths = build_paths()
    staging = paths.home / STAGING_NAME
    python = os.environ.get("PYTHON_BIN") or sys.executable
    commands: list[dict[str, Any]] = []
    if not _installed():
        staged_python = staging / "venv" / "bin" / "python"
        commands.extend([
            _command(
                "create_venv",
                [python, "-m", "venv", str(staging / "venv")],
                "https://docs.python.org/3/library/venv.html",
                50 * 1024 * 1024,
                f"remove owned staging directory {staging}",
            ),
            _command(
                "install_python",
                [str(staged_python), "-m", "pip", "install", "--require-hashes", "-r", str(ROOT / "requirements.lock")],
                "https://pypi.org/",
                250 * 1024 * 1024,
                f"remove owned staging directory {staging}",
            ),
            _command(
                "install_browser",
                [str(staged_python), "-m", "playwright", "install", "chromium"],
                "https://playwright.dev/python/docs/browsers",
                500 * 1024 * 1024,
                f"remove owned staging directory {staging}",
            ),
        ])
    if rebuild_ui:
        commands.extend([
            _command(
                "npm_ci",
                ["npm", "ci"],
                "https://docs.npmjs.com/cli/v11/commands/npm-ci",
                400 * 1024 * 1024,
                "remove frontend/node_modules if it was created by this approved run",
            ),
            _command(
                "build_ui",
                ["npm", "run", "build"],
                "https://nextjs.org/docs/app/api-reference/cli/next",
                200 * 1024 * 1024,
                "restore the previous generated frontend artifact",
            ),
        ])
    if ollama_model:
        commands.append(_command(
            "ollama_pull",
            ["ollama", "pull", ollama_model],
            "https://docs.ollama.com/cli",
            12 * 1024 * 1024 * 1024,
            f"remove only the explicitly installed model {ollama_model}",
        ))
    payload = {
        "schema_version": 1,
        "action": "install",
        "version": current_version(),
        "target": str(paths.home),
        "commands": commands,
        "disk_bytes": sum(command["disk_bytes"] for command in commands),
        "human_pauses": _human_pauses(),
        "rollback": "Only the owned staging directory and manifest-listed resources may be removed.",
    }
    return _hashed(payload)


def _run_command(command: dict[str, Any]) -> None:
    runner = os.environ.get("CORTEX_INSTALL_RUNNER")
    if runner:
        argv = [runner, json.dumps(command, sort_keys=True)]
        cwd = ROOT
    else:
        argv = command["argv"]
        cwd = ROOT / "frontend" if command["id"] in {"npm_ci", "build_ui"} else ROOT
    subprocess.run(argv, cwd=cwd, check=True)


def apply_install(plan: dict[str, Any], approved_hash: str) -> dict[str, Any]:
    if approved_hash != plan["plan_hash"]:
        raise PermissionError("approved plan hash does not match the current plan")
    if not plan["commands"]:
        return {"schema_version": 1, "status": "already_installed", "plan_hash": approved_hash}
    paths = build_paths()
    staging = paths.home / STAGING_NAME
    if staging.exists():
        raise RuntimeError(f"owned staging path already exists: {staging}")
    staging.mkdir(parents=True)
    try:
        for command in plan["commands"]:
            _run_command(command)
        staged_venv = staging / "venv"
        target_venv = paths.home / "venv"
        if any(command["id"] == "create_venv" for command in plan["commands"]):
            if not staged_venv.is_dir():
                raise RuntimeError("venv command did not produce the staged venv")
            if target_venv.exists():
                raise RuntimeError("target venv appeared during installation")
            staged_venv.replace(target_venv)
        install_dir = paths.home / "install"
        install_dir.mkdir(parents=True, exist_ok=True)
        manifest_path = install_dir / "owned.json"
        manifest = {
            "schema_version": 1,
            "owner": "cortex-bridge",
            "version": current_version(),
            "plan_hash": approved_hash,
            "resources": [str(target_venv), str(manifest_path)],
        }
        temporary = manifest_path.with_suffix(".tmp")
        temporary.write_text(json.dumps(manifest, indent=2, sort_keys=True), encoding="utf-8")
        temporary.replace(manifest_path)
        staging.rmdir()
    except BaseException:
        if staging.is_dir() and not staging.is_symlink():
            shutil.rmtree(staging)
        raise
    return {"schema_version": 1, "status": "installed", "plan_hash": approved_hash, "manifest": str(manifest_path)}


def _load_owned_manifest() -> dict[str, Any] | None:
    path = _owned_manifest_path()
    try:
        payload = json.loads(path.read_text(encoding="utf-8"))
    except (OSError, json.JSONDecodeError):
        return None
    if payload.get("owner") != "cortex-bridge" or not isinstance(payload.get("resources"), list):
        return None
    return payload


def build_uninstall_plan() -> dict[str, Any]:
    paths = build_paths()
    manifest = _load_owned_manifest()
    resources: list[str] = []
    for raw in (manifest or {}).get("resources", []):
        candidate = Path(str(raw)).resolve(strict=False)
        try:
            candidate.relative_to(paths.home)
        except ValueError:
            continue
        if candidate.exists() or candidate.is_symlink():
            resources.append(str(candidate))
    payload = {
        "schema_version": 1,
        "action": "uninstall",
        "version": current_version(),
        "target": str(paths.home),
        "resources": sorted(set(resources)),
        "preserved": ["settings", "database", "runs", "attachments", "browser profile", "logs"],
    }
    return _hashed(payload)


def apply_uninstall(plan: dict[str, Any], approved_hash: str) -> dict[str, Any]:
    if approved_hash != plan["plan_hash"]:
        raise PermissionError("approved uninstall plan hash does not match")
    home = build_paths().home
    removed: list[str] = []
    for raw in sorted(plan["resources"], key=lambda value: len(Path(value).parts), reverse=True):
        candidate = Path(raw).resolve(strict=False)
        candidate.relative_to(home)
        if candidate.is_symlink() or candidate.is_file():
            candidate.unlink(missing_ok=True)
            removed.append(str(candidate))
        elif candidate.is_dir():
            shutil.rmtree(candidate)
            removed.append(str(candidate))
    return {"schema_version": 1, "status": "uninstalled", "plan_hash": approved_hash, "removed": removed}


def doctor() -> dict[str, Any]:
    paths = build_paths()
    record = paths.pids / "console.json"
    process = classify(load_record(record), int(os.environ.get("PORT", "8420")))
    checks = [
        {"id": "python", "status": "pass" if sys.version_info >= (3, 11) else "fail", "required": True, "detail": sys.version.split()[0]},
        {"id": "cortex_home", "status": "pass" if paths.home.is_absolute() else "fail", "required": True, "detail": str(paths.home)},
        {"id": "deterministic", "status": "pass", "required": True, "detail": "available without Ollama or WebBridge"},
        {"id": "installation", "status": "pass" if _installed() else "warning", "required": False, "detail": "installed" if _installed() else "not installed"},
        {"id": "console_process", "status": process.state, "required": False, "detail": process.reason or process.state},
    ]
    return {
        "schema_version": 1,
        "version": current_version(),
        "ok": all(check["status"] == "pass" for check in checks if check["required"]),
        "cortex_home": str(paths.home),
        "modes": {"deterministic": True, "ollama": False, "webbridge": False},
        "checks": checks,
    }


def _print(payload: dict[str, Any], as_json: bool) -> None:
    if as_json:
        print(json.dumps(payload, sort_keys=True))
    else:
        print(json.dumps(payload, indent=2, sort_keys=True))


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser()
    subparsers = parser.add_subparsers(dest="action", required=True)
    install_parser = subparsers.add_parser("install")
    install_parser.add_argument("--dry-run", action="store_true")
    install_parser.add_argument("--approve-plan")
    install_parser.add_argument("--json", action="store_true")
    install_parser.add_argument("--rebuild-ui", action="store_true")
    install_parser.add_argument("--with-ollama-model")
    uninstall_parser = subparsers.add_parser("uninstall")
    uninstall_parser.add_argument("--dry-run", action="store_true")
    uninstall_parser.add_argument("--approve-plan")
    uninstall_parser.add_argument("--json", action="store_true")
    doctor_parser = subparsers.add_parser("doctor")
    doctor_parser.add_argument("--json", action="store_true")
    args = parser.parse_args(argv)
    try:
        if args.action == "doctor":
            _print(doctor(), args.json)
            return 0
        if args.action == "install":
            plan = build_install_plan(rebuild_ui=args.rebuild_ui, ollama_model=args.with_ollama_model)
            if args.dry_run:
                _print(plan, args.json)
                return 0
            if not args.approve_plan:
                raise PermissionError("install requires --dry-run or --approve-plan HASH")
            _print(apply_install(plan, args.approve_plan), args.json)
            return 0
        plan = build_uninstall_plan()
        if args.dry_run:
            _print(plan, args.json)
            return 0
        if not args.approve_plan:
            raise PermissionError("uninstall requires --dry-run or --approve-plan HASH")
        _print(apply_uninstall(plan, args.approve_plan), args.json)
        return 0
    except (OSError, ValueError, RuntimeError, PermissionError, subprocess.SubprocessError) as exc:
        payload = {"schema_version": 1, "status": "error", "error": str(exc)}
        _print(payload, getattr(args, "json", False))
        return 1


if __name__ == "__main__":
    raise SystemExit(main())
